#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    -- Default role for calling from the backend
    CREATE USER $DB_BACKEND_USER WITH PASSWORD '$DB_BACKEND_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $DB_BACKEND_USER;
    GRANT USAGE ON SCHEMA public TO $DB_BACKEND_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_BACKEND_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $DB_BACKEND_USER;

    -- DBA user
    CREATE USER $DB_ADMIN_USER WITH PASSWORD '$DB_ADMIN_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $DB_ADMIN_USER;
    ALTER USER $DB_ADMIN_USER WITH SUPERUSER;
EOSQL