events {}

http {
    upstream auth_service {
        server auth:3100;
    }
    upstream user_service {
        server user:3200;
    }
    upstream media_service {
        server media:3300;
    }

    # Redirect HTTP -> HTTPS
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    # HTTPS
    server {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/certs/embervault.crt;
        ssl_certificate_key /etc/nginx/certs/embervault.key;

        location /user/ {
            proxy_pass http://user_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /media/ {
            proxy_pass http://media_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}