FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

COPY .npmrc ./

RUN --mount=type=secret,id=github_token \
    export GITHUB_TOKEN=$(cat /run/secrets/github_token) && \
    npm ci

COPY . .

RUN npm run build

CMD ["npm", "run", "start"]
