FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

COPY .npmrc ./

RUN --mount=type=secret,id=auth_lib_token \
    export AUTH_LIB_TOKEN=$(cat /run/secrets/auth_lib_token) && \
    npm ci

COPY . .

RUN npm run build

CMD ["npm", "run", "start"]
