export const routes = {
	library: '/library',
	shared: '/shared',
	trash: '/trash',
	login: '/login',
	register: '/register',
	resetPasswordLink: '/reset-password-link',
	resetPassword: '/reset-password',
	profile: '/profile',
	adminPanel: '/admin',
	adminUsers: '/admin/users',
	adminResources: '/admin/resources',
}

export const languageLabels: Record<string, string> = {
	en: 'English',
	es: 'Español',
	cat: 'Català',
}

export const avgStaleTime = 5 * 60 * 1000 // 5 minutes

// This is used to map icons
export const FileTypeExtensions: Record<string, string[]> = {
	image: [
		'jpg',
		'jpeg',
		'png',
		'gif',
		'bmp',
		'svg',
		'webp',
		'tiff',
		'ico',
		'heic',
		'heif',
		'avif',
		'psd',
		'raw',
		'indd',
		'ai',
		'eps',
	],
	video: ['mp4', 'avi', 'mkv', 'mov', 'wmv', 'webm', 'flv', 'mpeg', 'mpg', '3gp', 'ogg'],
	document: ['doc', 'docx', 'odt', 'pages'],
	spreadsheet: ['xls', 'xlsx', 'csv', 'ods', 'numbers', 'tsv'],
	pdf: ['pdf'],
	presentation: ['ppt', 'pptx', 'odp', 'key'],
	audio: ['mp3', 'wav', 'ogg', 'flac', 'aac', 'm4a', 'opus', 'wma', 'aiff', 'aif', 'alac', 'amr'],
	archive: ['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'xz', 'tgz', 'tar.gz', 'xz', 'xz', 'bz2', 'lz', 'lzma'],
	text: ['txt', 'md', 'rtf'],
	code: [
		'json',
		'html',
		'css',
		'js',
		'ts',
		'py',
		'java',
		'cpp',
		'xml',
		'sh',
		'bat',
		'go',
		'rs',
		'swift',
		'kt',
		'dart',
		'sql',
		'yml',
		'yaml',
		'ini',
		'jsx',
		'tsx',
		'c',
		'cs',
		'php',
		'rb',
		'lua',
		'scala',
		'hs',
		'erl',
		'ex',
		'exs',
		'clj',
		'cljs',
		'groovy',
		'vbs',
		'ps1',
		'makefile',
		'dockerfile',
	],
	executable: ['exe', 'msi', 'apk', 'dmg', 'pkg', 'deb', 'rpm', 'appimage', 'bin'],
	book: ['epub', 'mobi', 'azw', 'fb2', 'djvu'],
}
